services:
  - type: web
    name: group-help-bot
    env: python
    plan: free
    buildCommand: pip install --no-cache-dir -r requirements.txt
    startCommand: python3 bot.py
    envVars:
      - key: BOT_TOKEN
        value: "8388594073:AAGxqqA6QriR7ZzWgQ2nCdZS7C04GrzhCKAyour-telegram-bot-token"
      - key: API_ID
        value: "23562992"
      - key: API_HASH
        value: "e070a310ca3e76ebc044146b9829237c"
      - key: MONGO_URI
        value: "mongodb+srv://rj5706603:O95nvJYxapyDHfkw@cluster0.fzmckei.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
